default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: renan

development:
  adapter: postgresql
  encoding: unicode
  database: keyvalue_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: keyvalue_test
  pool: 5
  host: localhost

production:
  pool: 20
